import { defineConfig } from 'token-jet';

// The site's tokens. Spacing and widths are px; type sizes are rem so text
// follows the browser's font-size setting. Colour tokens carry a dark value.
export default defineConfig({
  modes: {
    dark: '(prefers-color-scheme: dark)',
  },
  tokens: {
    size: {
      $group: { type: 'dimension' },
      x0: { value: '0px' },
      x4: { value: '4px' },
      x8: { value: '8px' },
      x12: { value: '12px' },
      x16: { value: '16px' },
      x24: { value: '24px' },
      x32: { value: '32px' },
      x48: { value: '48px' },
      x64: { value: '64px' },
      x80: { value: '80px' },
      x96: { value: '96px' },
      x128: { value: '128px' },
      x192: { value: '192px' },
      x256: { value: '256px' },
      x384: { value: '384px' },
      x512: { value: '512px' },
      x640: { value: '640px' },
      x768: { value: '768px' },
      x896: { value: '896px' },
      x1024: { value: '1024px' },
      x1152: { value: '1152px' },
      x1280: { value: '1280px' },
      x1408: { value: '1408px' },
      x1536: { value: '1536px' },
      x1664: { value: '1664px' },
      x1792: { value: '1792px' },
      x1920: { value: '1920px' },
    },
    font: {
      family: {
        $group: { type: 'fontFamily' },
        base: {
          value: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace',
        },
        header: { value: '{font.family.base}' },
        body: { value: '{font.family.base}' },
        data: { value: '{font.family.base}' },
      },
      size: {
        $group: { type: 'dimension' },
        base: { value: '1rem' },
        header: {
          xl: { value: '1.5rem' },
          lg: { value: '1.35rem' },
          md: { value: '1.2rem' },
          sm: { value: '1.1rem' },
          xs: { value: '1rem' },
        },
        body: {
          xl: { value: '1.3rem' },
          lg: { value: '1.15rem' },
          md: { value: '1rem' },
          sm: { value: '0.875rem' },
          xs: { value: '0.75rem' },
        },
        data: {
          xl: { value: '1.3rem' },
          lg: { value: '1.15rem' },
          md: { value: '1rem' },
          sm: { value: '0.875rem' },
          xs: { value: '0.75rem' },
        },
      },
      weight: {
        $group: { type: 'fontWeight' },
        header: { value: 700 },
        body: { value: 400 },
        data: { value: 500 },
      },
    },
    lineHeight: {
      $group: { type: 'number' },
      header: { value: 1.4 },
      body: { value: 1.5 },
      data: { value: 1.5 },
    },
    radius: {
      $group: { type: 'dimension' },
      container: { value: '3rem' },
      lg: { value: '1rem' },
      md: { value: '0.5rem' },
      sm: { value: '0.25rem' },
    },
    bg: {
      $group: { type: 'color' },
      base: { value: 'hsl(215deg 0% 100%)', dark: 'hsl(215deg 0% 0%)' },
      low: { value: 'hsl(215deg 10% 94%)', dark: 'hsl(215deg 30% 8%)' },
      mid: { value: 'hsl(215deg 12% 86%)', dark: 'hsl(215deg 25% 12%)' },
      high: { value: 'hsl(215deg 18% 78%)', dark: 'hsl(215deg 20% 18%)' },
    },
    content: {
      $group: { type: 'color' },
      default: { value: 'hsl(215deg 70% 0%)', dark: 'hsl(215deg 0% 100%)' },
      hover: { value: 'hsl(215deg 70% 2.5%)', dark: 'hsl(215deg 0% 92.5%)' },
      pressed: { value: 'hsl(215deg 70% 5%)', dark: 'hsl(215deg 0% 85%)' },
    },
    action: {
      $group: { type: 'color' },
      default: { value: 'hsl(215deg 70% 5%)', dark: 'hsl(215deg 5% 100%)' },
      hover: { value: 'hsl(215deg 70% 8%)', dark: 'hsl(215deg 5% 95%)' },
      pressed: { value: 'hsl(215deg 70% 11%)', dark: 'hsl(215deg 5% 90%)' },
    },
    muted: {
      $group: { type: 'color' },
      default: { value: 'hsl(215deg 10% 30%)', dark: 'hsl(215deg 5% 75%)' },
      hover: { value: 'hsl(215deg 10% 37.5%)', dark: 'hsl(215deg 5% 70%)' },
      pressed: { value: 'hsl(215deg 10% 35%)', dark: 'hsl(215deg 5% 65%)' },
    },
    inverted: {
      $group: { type: 'color' },
      default: { value: 'hsl(215deg 0% 0%)', dark: 'hsl(215deg 0% 100%)' },
      hover: { value: 'hsl(215deg 0% 5%)', dark: 'hsl(215deg 0% 95%)' },
      pressed: { value: 'hsl(215deg 0% 10%)', dark: 'hsl(215deg 0% 90%)' },
    },
  },
  types: {
    color: ['bg.**', 'content.**', 'action.**', 'muted.**', 'inverted.**'],
  },
});
