import type { Token } from './flatten.ts';
import type { ResolvedTokens } from './load.ts';
import { cssVariableReference, typeName } from './names.ts';

function jsdoc(token: Token): string {
  const parts: string[] = [];
  if (token.description !== undefined) parts.push(token.description);
  if (token.deprecated !== undefined) {
    parts.push(typeof token.deprecated === 'string' ? `@deprecated ${token.deprecated}` : '@deprecated');
  }
  return parts.length === 0 ? '' : `/** ${parts.join(' ')} */\n`;
}

// One alias per leaf, one union per group and per types entry, and the
// path-to-type map that token() is typed over.
export function emitTypes(resolved: ResolvedTokens): string {
  const { tokens, unions } = resolved;
  const out: string[] = ['// generated by token-jet. do not edit.', ''];

  for (const token of tokens) {
    out.push(`${jsdoc(token)}export type ${typeName(token.path)} = '${cssVariableReference(token.path)}';`);
  }
  out.push('');

  for (const union of unions) {
    out.push(`export type ${union.name} = ${union.paths.map(typeName).join(' | ')};`);
  }
  out.push('');

  out.push(`export type AnyToken = ${tokens.map((t) => typeName(t.path)).join(' | ')};`);
  out.push('');
  out.push(`export type TokenPath = ${tokens.map((t) => `'${t.path}'`).join(' | ')};`);
  out.push('');
  out.push('export interface TokenMap {');
  for (const token of tokens) out.push(`  '${token.path}': ${typeName(token.path)};`);
  out.push('}');

  return `${out.join('\n')}\n`;
}
