import type { ResolvedTokens } from './load.ts';
import { cssVariableReference } from './names.ts';

// token(path) returns the var() for a path. The signature is generic over the
// path literal so the return type is the exact var() literal, which is what
// lets a prop typed as SpaceToken accept it. A plain string is not a TokenPath,
// so a computed argument does not compile.
export function emitJs(resolved: ResolvedTokens): string {
  const out: string[] = [
    '// generated by token-jet. do not edit.',
    "import type { TokenMap, TokenPath } from './types.ts';",
    '',
    "export type * from './types.ts';",
    '',
    'const names = {',
  ];
  for (const token of resolved.tokens) {
    out.push(`  '${token.path}': '${cssVariableReference(token.path)}',`);
  }
  out.push('} as const;', '');
  out.push('export function token<P extends TokenPath>(path: P): TokenMap[P] {');
  out.push('  return names[path] as TokenMap[P];');
  out.push('}');
  return `${out.join('\n')}\n`;
}
