// generated by token-jet-generate. do not edit.
import type { SpaceToken } from './tokens/index.ts';
import styles from './padding.module.css';

const classes: Record<SpaceToken, string> = {
  'var(--space-x4)': styles.spaceX4,
  'var(--space-x16)': styles.spaceX16,
};

export function classNameForPadding(token: SpaceToken): string;
export function classNameForPadding(token: SpaceToken | undefined): string | undefined;
export function classNameForPadding(token: SpaceToken | undefined): string | undefined {
  return token === undefined ? undefined : classes[token];
}
