// generated by token-jet-generate. do not edit.
import type { SpacingToken } from './tokens/index.ts';
import styles from './padding.module.css';

const classes: Record<SpacingToken, string> = {
  'var(--space-x4)': styles.spaceX4,
  'var(--space-x16)': styles.spaceX16,
};

export function classNameForPadding(token: SpacingToken): string;
export function classNameForPadding(token: SpacingToken | undefined): string | undefined;
export function classNameForPadding(token: SpacingToken | undefined): string | undefined {
  return token === undefined ? undefined : classes[token];
}
