// generated by token-jet-generate. do not edit.
import type { Meta, StoryObj } from '@storybook/react';

const meta: Meta = { title: 'Tokens/Space' };
export default meta;

export const SpaceX4: StoryObj = {
  name: 'space.x4',
  render: () => <div style={{ width: '4px' }} />,
};

export const SpaceX16: StoryObj = {
  name: 'space.x16',
  render: () => <div style={{ width: '16px' }} />,
};
