// generated by token-jet-generate. do not edit.
import type { SpaceToken } from './tokens/index.ts';

export const spaceValue: Record<SpaceToken, string> = {
  'var(--space-x4)': '4px',
  'var(--space-x16)': '16px',
};
