// generated by token-jet-generate. do not edit.
import type { SurfaceToken } from './tokens/index.ts';
import styles from './surface.module.css';

const classes: Record<SurfaceToken, string> = {
  'var(--bg-page)': styles.bgPage,
  'var(--bg-card)': styles.bgCard,
};

export function classNameForSurface(token: SurfaceToken): string;
export function classNameForSurface(token: SurfaceToken | undefined): string | undefined;
export function classNameForSurface(token: SurfaceToken | undefined): string | undefined {
  return token === undefined ? undefined : classes[token];
}
