// generated by token-jet-generate. do not edit.
import type { BgPage, BgCard } from './tokens/index.ts';

type Selected = BgPage | BgCard;
import styles from './surface.module.css';

const classes: Record<Selected, string> = {
  'var(--bg-page)': styles.bgPage,
  'var(--bg-card)': styles.bgCard,
};

export function classNameForSurface(token: Selected): string;
export function classNameForSurface(token: Selected | undefined): string | undefined;
export function classNameForSurface(token: Selected | undefined): string | undefined {
  return token === undefined ? undefined : classes[token];
}
