import { typeName } from 'token-jet';
import type { ManifestToken } from 'token-jet';

import type { EntryContext } from '../index.ts';

export const HEADER = '// generated by token-jet-generate. do not edit.';

export function className(token: ManifestToken): string {
  const pascal = typeName(token.path);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

export function selectedTypeName(context: EntryContext): string {
  return context.union?.name ?? 'Selected';
}

export function selectedTypeImport(tokens: readonly ManifestToken[], context: EntryContext): string {
  const names = context.union === undefined ? tokens.map((t) => typeName(t.path)) : [context.union.name];
  const lines = [`import type { ${names.join(', ')} } from '${context.tokens}';`];
  if (context.union === undefined) lines.push('', `type Selected = ${names.join(' | ')};`);
  return lines.join('\n');
}
