import { typeName } from 'token-jet';
import type { ManifestToken } from 'token-jet';

import type { EntryContext } from '../index.ts';

export const HEADER = '// generated by token-jet-generate. do not edit.';

export function className(token: ManifestToken): string {
  const pascal = typeName(token.path);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

export function selectedTypeName(context: EntryContext): string {
  return context.union.name;
}

export function selectedTypeImport(context: EntryContext): string {
  const specifier = `'${context.tokens}'`;
  return `import type { ${context.union.name} } from ${specifier};`;
}
