// generated by token-jet. do not edit.
import type { TokenMap, TokenPath } from './types.ts';

export type * from './types.ts';

const names = {
  'space.x4': 'var(--space-x4)',
  'space.x16': 'var(--space-x16)',
  'weight.bold': 'var(--weight-bold)',
  'family.body': 'var(--family-body)',
  'ratio.golden': 'var(--ratio-golden)',
  'gray.50': 'var(--gray-50)',
  'gray.900': 'var(--gray-900)',
  'bg.page': 'var(--bg-page)',
  'bg.card': 'var(--bg-card)',
  'content.regular': 'var(--content-regular)',
  'content.body': 'var(--content-body)',
} as const;

export function token<P extends TokenPath>(path: P): TokenMap[P] {
  return names[path] as TokenMap[P];
}
