// generated by token-jet. do not edit.

export type SpaceX4 = 'var(--space-x4)';
/** The default gap. */
export type SpaceX16 = 'var(--space-x16)';
export type WeightBold = 'var(--weight-bold)';
export type FamilyBody = 'var(--family-body)';
export type RatioGolden = 'var(--ratio-golden)';
export type Gray50 = 'var(--gray-50)';
export type Gray900 = 'var(--gray-900)';
export type BgPage = 'var(--bg-page)';
export type BgCard = 'var(--bg-card)';
/** @deprecated use content.body */
export type ContentRegular = 'var(--content-regular)';
export type ContentBody = 'var(--content-body)';

export type SpaceToken = SpaceX4 | SpaceX16;
export type WeightToken = WeightBold;
export type FamilyToken = FamilyBody;
export type RatioToken = RatioGolden;
export type GrayToken = Gray50 | Gray900;
export type BgToken = BgPage | BgCard;
export type ContentToken = ContentRegular | ContentBody;
export type ColorToken = Gray50 | Gray900 | BgPage | BgCard | ContentRegular | ContentBody;
export type SurfaceToken = BgPage | BgCard;

export type AnyToken = SpaceX4 | SpaceX16 | WeightBold | FamilyBody | RatioGolden | Gray50 | Gray900 | BgPage | BgCard | ContentRegular | ContentBody;

export type TokenPath = 'space.x4' | 'space.x16' | 'weight.bold' | 'family.body' | 'ratio.golden' | 'gray.50' | 'gray.900' | 'bg.page' | 'bg.card' | 'content.regular' | 'content.body';

export interface TokenMap {
  'space.x4': SpaceX4;
  'space.x16': SpaceX16;
  'weight.bold': WeightBold;
  'family.body': FamilyBody;
  'ratio.golden': RatioGolden;
  'gray.50': Gray50;
  'gray.900': Gray900;
  'bg.page': BgPage;
  'bg.card': BgCard;
  'content.regular': ContentRegular;
  'content.body': ContentBody;
}
